FROM ruby:3.1

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /price_tracker
WORKDIR /price_tracker

COPY Gemfile Gemfile.lock ./
RUN bundle install

ADD . ./

CMD ["rails", "server", "-e", "production", "-b", "0.0.0.0"]